import assert from "node:assert/strict";
import { mkdir, writeFile, rm } from "node:fs/promises";
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
const require = createRequire(import.meta.url);
const { chromium } = require("playwright");
const origin = process.env.SMOKE_UI_ORIGIN ?? "http://127.0.0.1:5178";
const testKey = process.env.SMOKE_DEV_AUTH_SECRET ?? "ui-smoke-test-only";
const output = process.env.SMOKE_OUTPUT ?? "/tmp/management-ui-smoke";
await mkdir(output, { recursive: true });
await rm(`${output}/result.json`, { force: true });
const browser = await chromium.launch({ executablePath: "/usr/bin/chromium", headless: true, args: ["--no-sandbox"] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, permissions: ["clipboard-read", "clipboard-write"] });
const page = await context.newPage();
const errors = []; const checks = [];
page.on("pageerror", error => errors.push(error.message));
const check = (name, passed = true) => { assert.ok(passed, name); checks.push(name); console.log(`PASS ${name}`); };
try {
	await page.goto(origin); await page.getByRole("link", { name: "使用 GitHub 登录" }).waitFor();
	check("anonymous browser receives the GitHub login gate");
	const login = await context.request.post(`${origin}/api/auth/development`, { headers: { Origin: origin }, data: { secret: testKey } });
	assert.equal(login.status(), 200, await login.text());
	const me = await login.json(); const fixtures = JSON.parse(execFileSync(new URL("../../node_modules/.bin/tsx", import.meta.url).pathname, [new URL("./seed-smoke.ts", import.meta.url).pathname], { encoding: "utf8" })); await page.reload(); await page.getByRole("heading", { name: "仪表盘", exact: true }).waitFor();
	check("real local API session bootstraps GET /api/me");
	assert.equal(await page.evaluate(() => localStorage.length), 0); check("no session token or credential is saved in localStorage");
	await page.screenshot({ path: `${output}/dashboard-desktop.png`, fullPage: true });
	for (const [route, heading] of [["articles", "文章"], ["media", "媒体库"], ["settings", "站点设置"], ["navigation", "导航"], ["icons", "网站图标"], ["comments", "评论"], ["friends", "友链申请与排序"], ["publications", "发布记录"], ["maintenance", "维护与备份"]]) {
		await page.goto(`${origin}/#${route}`); await page.getByRole("heading", { name: heading, exact: true }).waitFor();
		check(`real API page renders: ${route}`);
	}

	await page.goto(`${origin}/#comments?articleId=${fixtures.articleId}`);
	let parentCard = page.locator(".comment-card").filter({ has: page.getByText(fixtures.parentName, { exact: true }) });
	await parentCard.getByRole("button", { name: "禁言", exact: true }).click(); await page.getByLabel("原因（仅管理可见）").fill("真实本地禁言验收"); await page.getByRole("button", { name: "确认禁言" }).click(); await page.getByText("该访客已禁言。", { exact: true }).waitFor();
	let commentsData = (await (await context.request.get(`${origin}/api/comments`)).json()).items; assert.equal(commentsData.find(item => item.id === fixtures.parentId).banned, true);
	await parentCard.getByRole("button", { name: "解禁", exact: true }).click(); await page.getByText("该访客已解禁。", { exact: true }).waitFor(); commentsData = (await (await context.request.get(`${origin}/api/comments`)).json()).items; assert.equal(commentsData.find(item => item.id === fixtures.parentId).banned, false); check("real moderation bans and unbans the same visitor");
	await parentCard.getByRole("button", { name: "删除", exact: true }).click(); await page.getByRole("button", { name: "确认删除", exact: true }).click(); await page.getByText("评论已软删除，回复关系保留。", { exact: true }).waitFor();
	commentsData = (await (await context.request.get(`${origin}/api/comments`)).json()).items; assert.equal(commentsData.find(item => item.id === fixtures.parentId).deleted, true); assert.equal(commentsData.find(item => item.id === fixtures.replyId).parentId, fixtures.parentId); check("soft deletion retains the stable parent and child relationship");
	await page.goto(`${origin}/#friends`); let friendRow = page.locator("tr").filter({ has: page.getByText(fixtures.approveName, { exact: true }) }); await friendRow.getByRole("button", { name: "批准", exact: true }).click(); await page.getByText("审核已通过；需发布并核验上线后发送通知。", { exact: true }).waitFor();
	friendRow = page.locator("tr").filter({ has: page.getByText(fixtures.rejectName, { exact: true }) }); await friendRow.getByRole("button", { name: "拒绝", exact: true }).click(); await page.getByLabel(/^拒绝理由/).fill("站点信息尚不完整"); await page.getByRole("button", { name: "确认拒绝并记录理由", exact: true }).click(); await page.getByText("拒绝结果已保存；邮件按持久任务发送。", { exact: true }).waitFor();
	let friendsData = (await (await context.request.get(`${origin}/api/friends`)).json()).items; assert.equal(friendsData.find(item => item.id === fixtures.approveId).status, "approved"); assert.equal(friendsData.find(item => item.id === fixtures.rejectId).reason, "站点信息尚不完整"); assert.equal(friendsData.find(item => item.id === fixtures.approveId).live, false);
	const outbox = (await (await context.request.get(`${origin}/api/maintenance/outbox`)).json()).items; assert.equal(outbox.find(item => item.friendId === fixtures.approveId).status, "waiting"); assert.equal(outbox.find(item => item.friendId === fixtures.rejectId).status, "pending"); check("friend approval/rejection persist outcomes and distinct delayed mail states");
	await page.locator("tr").filter({ has: page.getByText(fixtures.approveName, { exact: true }) }).getByRole("button", { name: "查看通知记录", exact: true }).click(); await page.getByRole("dialog").getByText("通过通知", { exact: true }).waitFor(); await page.getByRole("button", { name: "关闭弹窗" }).click();
	await page.getByRole("button", { name: "分组与排序", exact: true }).click(); await page.getByLabel(`${fixtures.approveName} 分组`).fill("验收分组"); await page.getByRole("button", { name: "保存分组排序", exact: true }).click(); await page.getByText("分组和排序已保存。", { exact: true }).waitFor(); friendsData = (await (await context.request.get(`${origin}/api/friends`)).json()).items; assert.equal(friendsData.find(item => item.id === fixtures.approveId).group, "验收分组"); check("friend grouping and sorting use real versioned API writes");
	await page.goto(`${origin}/#articles`); await page.getByRole("button", { name: "＋ 新建草稿" }).click();
	const name = `浏览器验收-${Date.now()}`;
	await page.getByLabel("标题", { exact: true }).fill(name); await page.getByLabel(/^固定 slug/).fill(name); await page.getByRole("button", { name: "创建草稿", exact: true }).click();
	await page.getByLabel("文章源码").waitFor();
	const list = await context.request.get(`${origin}/api/articles`); const created = (await list.json()).items.find(item => item.slug === name);
	check("new draft has stable ID and is private", Boolean(created?.id && created.draft && !created.publishedVersion));
	const raw = "---\ntitle: '浏览器验收' #保留注释\nunknown: { a: 1, text: 'keep  spacing' }\n---\n# 源码\n\n<Custom>HTML 保留</Custom>\n";
	await page.getByLabel("文章源码").fill(raw); await page.getByRole("button", { name: /^保存草稿/ }).click(); await page.getByText("草稿已保存；生产内容尚未改变。").waitFor();
	let article = await (await context.request.get(`${origin}/api/articles/${created.id}`)).json(); assert.equal(article.raw, raw); check("source save preserves unknown YAML, comments, and HTML exactly");
	await page.getByLabel("标题", { exact: true }).fill("仅改标题"); await page.getByRole("button", { name: /^保存草稿/ }).click();
	await page.getByText("草稿已保存；生产内容尚未改变。").waitFor(); article = await (await context.request.get(`${origin}/api/articles/${created.id}`)).json(); assert.equal(article.raw, raw.replace("'浏览器验收'", "仅改标题")); assert.equal(article.slug, name); check("metadata changes preserve all unowned bytes and the stable slug");
	await page.getByLabel("文章源码").fill(article.raw + "\n未保存保护验收"); await page.getByRole("button", { name: "历史与比较" }).click(); await page.getByRole("button", { name: /^v1/ }).click(); assert.equal(await page.getByRole("button", { name: "恢复为新草稿" }).isDisabled(), true); check("history restore cannot overwrite an unsaved local draft"); await page.getByRole("button", { name: "写作", exact: true }).click();
	await page.getByLabel("文章源码").fill(article.raw + "\n本地编辑");
	const external = await context.request.put(`${origin}/api/articles/${created.id}`, { headers: { Origin: origin, "X-CSRF-Token": me.csrf }, data: { ...article, raw: article.raw + "\n远端修改", version: article.version, draft: true } }); assert.equal(external.status(), 200);
	await page.getByRole("button", { name: /^保存草稿/ }).click(); await page.getByRole("dialog", { name: "外部修改冲突 · 409" }).waitFor(); check("409 preserves local text and displays actual remote difference");
	await page.getByRole("button", { name: "保留当前编辑，以最新版本作为合并基线" }).click(); await page.getByRole("button", { name: /^保存草稿/ }).click(); await page.getByText("草稿已保存；生产内容尚未改变。").waitFor();
	await page.getByRole("button", { name: "历史与比较" }).click(); await page.getByRole("button", { name: /^v1/ }).click(); await page.getByRole("button", { name: "恢复为新草稿" }).click(); await page.getByRole("button", { name: "确认恢复", exact: true }).click(); await page.getByText("历史版本已恢复为新的私有草稿。").waitFor();
	article = await (await context.request.get(`${origin}/api/articles/${created.id}`)).json(); assert.equal(article.id, created.id); assert.ok(article.version >= 5); check("history restore creates a new private version and retains stable ID");
	await page.getByRole("button", { name: "写作", exact: true }).click(); await page.getByLabel("文章源码").fill("---\ntitle: 写作工具验收\n---\n# 写作\n\n普通段落\n"); await page.getByRole("button", { name: "可视编辑", exact: true }).click(); await page.locator(".tiptap").waitFor(); check("safe CommonMark enters the real TipTap editor");
	await page.locator(".tiptap").click(); await page.keyboard.press("Control+End"); await page.keyboard.press("Enter"); await page.keyboard.type("/heading"); await page.getByRole("listbox", { name: "斜杠菜单" }).waitFor(); await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter"); await page.locator(".tiptap h2").waitFor({ state: "attached" }); check("English slash search and keyboard selection insert a heading");
	await page.locator(".tiptap").click(); await page.keyboard.press("Control+k"); await page.getByRole("dialog", { name: "插入链接" }).waitFor(); await page.getByRole("button", { name: "关闭弹窗" }).click(); check("Ctrl+K opens the link dialog");
	await page.getByRole("button", { name: "公式", exact: true }).click(); await page.getByLabel("LaTeX", { exact: true }).fill("x^2"); await page.getByRole("button", { name: "应用", exact: true }).click(); await page.locator(".katex").first().waitFor(); check("formula uses real KaTeX rendering");
	await page.getByRole("button", { name: "表格", exact: true }).click(); await page.getByRole("button", { name: "加行", exact: true }).waitFor(); await page.getByRole("button", { name: "加行", exact: true }).click(); check("advanced table controls add a real row"); await page.getByRole("button", { name: "表格后继续写作", exact: true }).click();

	await page.locator(".tiptap > p").last().click(); await page.keyboard.press("Control+End"); await page.keyboard.press("Enter");
	await page.evaluate(async () => navigator.clipboard.writeText("**Markdown 粘贴验收**")); await page.keyboard.press("Control+v"); await page.locator(".tiptap strong").filter({ hasText: "Markdown 粘贴验收" }).waitFor(); check("real clipboard Markdown paste preserves bold formatting");
	await page.keyboard.press("Home"); await page.keyboard.press("Shift+End"); await page.locator(".bubble-menu").waitFor(); check("text selection opens the floating format menu");
	await page.keyboard.press("ArrowRight"); await page.keyboard.press("Control+End"); await page.keyboard.press("Enter"); await page.keyboard.insertText("/标题"); await page.getByRole("option", { name: /标题 3/ }).click(); check("Chinese slash search inserts a heading");
	await page.getByRole("button", { name: "代码语言", exact: true }).click(); await page.getByLabel("搜索语言", { exact: true }).fill("type"); await page.getByRole("button", { name: "typescript", exact: true }).click(); await page.locator(".tiptap:focus").waitFor(); await page.keyboard.insertText("const accepted: boolean = true;"); await page.locator(".tiptap pre code.language-typescript").filter({ hasText: "const accepted: boolean = true;" }).waitFor(); check("code language search configures a real TypeScript code block");
	await page.getByRole("button", { name: "Mermaid", exact: true }).click(); await page.locator(".tiptap pre code.language-mermaid").waitFor(); check("Mermaid command inserts a diagram source block");
	await page.getByRole("button", { name: "源码", exact: true }).click(); const written = await page.getByLabel("文章源码").inputValue(); assert.match(written, /\$x\^2\$/); assert.match(written, /\|/); assert.match(written, /```typescript\nconst accepted: boolean = true;/); assert.match(written, /```mermaid/); assert.match(written, /graph TD/); await page.screenshot({ path: `${output}/editor-source-desktop.png`, fullPage: true }); check("visual writing serializes formulas, tables, TypeScript and Mermaid source to Markdown");
	await page.getByRole("button", { name: /^保存草稿/ }).click(); await page.getByText("草稿已保存；生产内容尚未改变。").waitFor();

	await page.getByRole("button", { name: "发布…", exact: true }).click(); const blockedPublication = page.waitForResponse(response => response.url().endsWith("/api/publications") && response.request().method() === "POST"); await page.getByRole("button", { name: "创建发布任务", exact: true }).click(); const blockedResponse = await blockedPublication; assert.equal(blockedResponse.status(), 403); await page.getByRole("dialog").getByRole("alert").waitFor(); const blockedData = await blockedResponse.json(); assert.equal(blockedData.error.code, "PRODUCTION_REQUIRED"); await page.getByRole("button", { name: "关闭弹窗" }).click(); check("development publication is denied explicitly and never reports production success");
	await page.goto(`${origin}/#media`); await page.getByRole("button", { name: "＋ 本地上传" }).click();
	await page.getByLabel("本地图片（最多 10 MB）").setInputFiles({ name: `smoke-pixel-${name}.png`, mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l0AAAAASUVORK5CYII=", "base64") }); await page.getByLabel("替代文本 alt").fill("测试替代文本"); await page.getByLabel("图注 caption").fill("测试图注"); await page.getByRole("button", { name: "上传到私有媒体库" }).click(); await page.getByText(`smoke-pixel-${name}.png`, { exact: true }).waitFor();
	const media = (await (await context.request.get(`${origin}/api/media`)).json()).items.find(item => item.filename === `smoke-pixel-${name}.png`); assert.equal(media.status, "private"); assert.equal(media.alt, "测试替代文本"); assert.equal(media.caption, "测试图注"); const anonymous = await browser.newContext(); const privateRead = await anonymous.request.get(`${origin}/api/media/${media.id}/content`); assert.equal(privateRead.status(), 401); await anonymous.close(); check("local upload stores distinct alt/caption and denies anonymous private reads");

	await page.goto(`${origin}/#settings`); await page.getByLabel("站点标题", { exact: true }).waitFor();
	const settingsBefore = await (await context.request.get(`${origin}/api/settings`)).json();
	const settingsTitle = `设置验收-${Date.now()}`; await page.getByLabel("站点标题", { exact: true }).fill(settingsTitle); await page.getByRole("button", { name: /^保存设置草稿/ }).click(); await page.getByText("设置草稿已保存；请单独发布以更新公开站点。").waitFor();
	const settingsAfter = await (await context.request.get(`${origin}/api/settings`)).json(); assert.equal(settingsAfter.values.title, settingsTitle); assert.equal(settingsAfter.values.signature, settingsBefore.values.signature); check("settings save updates one explicit field and preserves the signature");
	await page.goto(`${origin}/#navigation`); await page.locator(".navigation-list .panel").first().waitFor();
	const navBefore = await (await context.request.get(`${origin}/api/navigation`)).json();
	await page.locator(".navigation-list .panel").first().getByLabel("名称", { exact: true }).first().fill(`本地导航-${name}`); await page.getByRole("button", { name: "保存导航草稿", exact: true }).click(); await page.getByText("导航草稿已保存。", { exact: true }).waitFor();
	const navAfter = await (await context.request.get(`${origin}/api/navigation`)).json(); assert.equal(navAfter.items[0].name, `本地导航-${name}`); assert.deepEqual(navAfter.items.map(item => item.id), navBefore.items.map(item => item.id)); assert.deepEqual(navAfter.items[0].children, navBefore.items[0].children?.map((child, order) => ({ ...child, order }))); check("navigation edit preserves stable group IDs and child menus");
	await page.goto(`${origin}/#icons`); await page.locator(".icon-slot").first().waitFor(); assert.equal(await page.locator(".icon-slot").count(), 6);
	await page.locator(".icon-slot").filter({ has: page.getByRole("heading", { name: "favicon-96x96.png", exact: true }) }).locator('input[type="file"]').setInputFiles({ name: "favicon-96x96.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l0AAAAASUVORK5CYII=", "base64") });
	await page.getByRole("button", { name: "上传并保存图标草稿", exact: true }).click(); await page.getByText("图标已保存为私有配置，发布后应用到公开站点。").waitFor();
	const iconsSettings = await (await context.request.get(`${origin}/api/settings`)).json(); assert.match(iconsSettings.values.icons["favicon-96x96.png"], /^media:/); assert.equal(iconsSettings.values.title, settingsTitle); check("six icon slots save a private media reference without overwriting other settings");

	const iconNames = ["favicon.svg", "favicon.ico", "favicon-96x96.png", "apple-touch-icon.png", "web-app-manifest-192x192.png", "web-app-manifest-512x512.png"];
	const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9l0AAAAASUVORK5CYII=", "base64"); const ico = Buffer.alloc(22 + png.length); ico.writeUInt16LE(1, 2); ico.writeUInt16LE(1, 4); ico[6] = ico[7] = 1; ico.writeUInt16LE(1, 10); ico.writeUInt16LE(32, 12); ico.writeUInt32LE(png.length, 14); ico.writeUInt32LE(22, 18); png.copy(ico, 22);
	const archiveFiles = Object.fromEntries(iconNames.map(filename => [`icons/${filename}`, filename.endsWith(".svg") ? Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96"><rect width="96" height="96" fill="#1d6b58"/></svg>') : filename.endsWith(".ico") ? ico : png])); const { zipSync } = require("fflate");
	await page.locator('.page-title input[type="file"]').setInputFiles({ name: "six-icons.zip", mimeType: "application/zip", buffer: Buffer.from(zipSync(archiveFiles)) }); await page.waitForFunction(() => document.querySelectorAll(".icon-slot .tag.amber").length === 6); await page.getByRole("button", { name: "上传并保存图标草稿", exact: true }).click(); await page.getByText("图标已保存为私有配置，发布后应用到公开站点。").waitFor();
	const packageSettings = await (await context.request.get(`${origin}/api/settings`)).json(); assert.deepEqual(Object.keys(packageSettings.values.icons).sort(), iconNames.sort()); assert.ok(Object.values(packageSettings.values.icons).every(value => /^media:/.test(value))); assert.equal(packageSettings.values.title, settingsTitle); check("filename-recognized ZIP imports all six icon slots into private configuration");
	await page.goto(`${origin}/#maintenance`); await page.getByRole("heading", { name: "维护与备份", exact: true }).waitFor();
	await page.locator(".operation-card").filter({ has: page.getByRole("heading", { name: "创建私有备份", exact: true }) }).getByRole("button", { name: "创建维护任务 →" }).click(); await page.getByRole("dialog").getByRole("button", { name: "创建任务", exact: true }).click(); await page.getByText("维护任务已创建；以任务结果为准。").waitFor();
	let backupTask;
	for (let attempt = 0; attempt < 70; attempt++) { const tasks = await (await context.request.get(`${origin}/api/maintenance/tasks`)).json(); backupTask = tasks.items.find(item => item.type === "backup"); if (["succeeded", "failed"].includes(backupTask?.status)) break; await new Promise(resolve => setTimeout(resolve, 500)); }
	assert.equal(backupTask?.status, "succeeded", JSON.stringify(backupTask)); const backups = await (await context.request.get(`${origin}/api/maintenance/backups`)).json(); assert.ok(backups.items.some(item => item.sha256 && item.mediaCount >= 1)); check("maintenance creates a durable backup containing checksummed private media");

	await page.getByRole("button", { name: "刷新备份", exact: true }).click(); await page.locator(".backup-catalog tbody tr").first().waitFor(); await page.locator(".backup-catalog tbody tr").first().getByRole("button", { name: "验证此备份", exact: true }).click(); await page.getByRole("dialog").getByRole("button", { name: "创建任务", exact: true }).click(); await page.getByText("维护任务已创建；以任务结果为准。").waitFor();
	let verifyTask; for (let attempt = 0; attempt < 70; attempt++) { const tasks = await (await context.request.get(`${origin}/api/maintenance/tasks`)).json(); verifyTask = tasks.items.find(item => item.type === "verify-backup"); if (["succeeded", "failed"].includes(verifyTask?.status)) break; await new Promise(resolve => setTimeout(resolve, 500)); }
	assert.equal(verifyTask?.status, "succeeded", JSON.stringify(verifyTask)); const stillArticle = await (await context.request.get(`${origin}/api/articles/${created.id}`)).json(); assert.equal(stillArticle.id, created.id); check("backup validation verifies private bytes and records without restoring current data"); await page.getByRole("button", { name: "刷新任务", exact: true }).click(); await page.screenshot({ path: `${output}/maintenance-desktop.png`, fullPage: true });
	await page.setViewportSize({ width: 390, height: 844 }); await page.goto(`${origin}/#dashboard`); await page.waitForFunction(() => { const drawer = document.querySelector(".sidebar:not(.open)"); return drawer && drawer.getBoundingClientRect().right <= 0.5; }); await page.screenshot({ path: `${output}/dashboard-mobile-closed.png`, fullPage: true }); await page.getByRole("button", { name: "展开菜单" }).click(); await page.waitForFunction(() => { const drawer = document.querySelector(".sidebar.open"); if (!drawer) return false; const rect = drawer.getBoundingClientRect(); return Math.abs(rect.left) < 0.5 && rect.right <= innerWidth && rect.width >= 180; }); await page.getByRole("navigation", { name: "主导航" }).waitFor(); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true); await page.screenshot({ path: `${output}/dashboard-mobile.png`, fullPage: true }); await page.screenshot({ path: `${output}/dashboard-mobile-open.png`, fullPage: true }); await page.getByRole("button", { name: "收起菜单", exact: true }).click(); await page.waitForFunction(() => document.querySelector(".sidebar")?.getBoundingClientRect().right <= 0.5); await page.screenshot({ path: `${output}/dashboard-mobile-closed.png`, fullPage: true }); check("mobile drawer opens and closes fully with no horizontal overflow");
	check("no unhandled browser exceptions", errors.length === 0);
	await writeFile(`${output}/result.json`, JSON.stringify({ passed: checks.length, checks, browserErrors: errors, note: "真实本地API与隔离SQLite；开发会话用于验收。GitHub OAuth与生产服务需要外部配置，未在本测试声称通过。" }, null, 2));
	console.log(JSON.stringify({ passed: checks.length, output, browserErrors: errors }));
} catch (error) { await page.screenshot({ path: `${output}/failure.png`, fullPage: true }); await writeFile(`${output}/failure.json`, JSON.stringify({ checks, browserErrors: errors, error: String(error), body: (await page.locator("body").innerText()).slice(-2500), editorHtml: await page.locator(".tiptap").evaluate(element => element.innerHTML).catch(() => "") }, null, 2)); throw error; } finally { await browser.close(); }
