import { afterEach, describe, expect, it, vi } from "vitest";
import { ApiClient, ApiError } from "./api";
afterEach(() => vi.unstubAllGlobals());
describe("same-origin authenticated API contract", () => {
	it("reads without writing CSRF and never caches responses", async () => { const request = vi.fn(async () => new Response(JSON.stringify({ user: { id: 7 }, csrf: "session-csrf" }))); vi.stubGlobal("fetch", request); const client = new ApiClient(); await client.get("/me"); expect(request).toHaveBeenCalledWith("/api/me", expect.objectContaining({ credentials: "same-origin", cache: "no-store", method: "GET" })); });
	it("prevents unauthenticated writes", async () => { const request = vi.fn(); vi.stubGlobal("fetch", request); await expect(new ApiClient().post("/articles", {})).rejects.toMatchObject({ status: 403, code: "csrf_missing" }); expect(request).not.toHaveBeenCalled(); });
	it("attaches session CSRF to every write and uses exact raw payload", async () => { const request = vi.fn(async () => new Response("{}")); vi.stubGlobal("fetch", request); const client = new ApiClient(); client.setCsrf("memory-only"); const raw = "---\n# comment\nunknown: {x: 'y'}\n---\n<MDX />"; await client.put("/articles/abc", { raw, version: 1, draft: true }); expect(request.mock.calls[0]).toEqual(["/api/articles/abc", expect.objectContaining({ headers: expect.objectContaining({ "X-CSRF-Token": "memory-only" }), body: JSON.stringify({ raw, version: 1, draft: true }) })]); });
	it("preserves server conflict details for a real 409 merge", async () => { vi.stubGlobal("fetch", async () => new Response(JSON.stringify({ error: { code: "version_conflict", message: "版本冲突", details: { current: { raw: "remote", version: 3 } } } }), { status: 409 })); const client = new ApiClient(); client.setCsrf("csrf"); await expect(client.put("/articles/abc", {})).rejects.toMatchObject({ status: 409, details: { current: { raw: "remote", version: 3 } } }); });
	it("retains configuration failures as failures instead of fake success", async () => { vi.stubGlobal("fetch", async () => new Response(JSON.stringify({ error: { code: "service_unconfigured", message: "缺少媒体存储配置" } }), { status: 503 })); await expect(new ApiClient().get("/media")).rejects.toBeInstanceOf(ApiError); });
});
