import { useState } from "react";
import { api, key, type MediaItem } from "./api";
import { ActionStatus, Empty, ErrorBox, Field, Modal, PageTitle, Tag, Time, useAction, useResource } from "./shared";
export function MediaLibrary({ select }: { select?: (item: MediaItem) => void }) {
	const resource = useResource(() => api.get<{ items: MediaItem[] }>("/media")); const [upload, setUpload] = useState(false); const [importOpen, setImportOpen] = useState(false); const [editing, setEditing] = useState<MediaItem>(); const [query, setQuery] = useState(""); const [visibility, setVisibility] = useState("all");
	const items = resource.data?.items.filter(item => `${item.filename} ${item.alt} ${item.caption}`.toLowerCase().includes(query.toLowerCase()) && (visibility === "all" || item.status === visibility)) ?? [];
	return <><PageTitle title={select ? "媒体选择" : "媒体库"} description="草稿媒体私有保存。替代文本描述图像；图注作为文章中可见的说明。" actions={<><button onClick={() => setImportOpen(true)}>外链导入</button><button className="primary" onClick={() => setUpload(true)}>＋ 本地上传</button></>}/><ErrorBox error={resource.error} retry={() => void resource.refresh()}/><div className="row between filter-bar"><input aria-label="搜索媒体" placeholder="搜索文件名、替代文本或图注" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="媒体可见性" value={visibility} onChange={e => setVisibility(e.target.value)}><option value="all">全部媒体</option><option value="private">私有</option><option value="pending">待验证上传</option><option value="published">已发布</option></select></div>{resource.loading && !resource.data ? <Empty>正在读取媒体…</Empty> : !items.length ? <Empty>没有媒体。上传不会自动将资源公开。</Empty> : <div className="media-grid">{items.map(item => <div className="panel media-card" key={item.id}><div className="media-thumbnail">{item.status !== "pending" && item.contentType.startsWith("image/") && item.contentType !== "image/svg+xml" ? <img loading="lazy" alt={item.alt || "媒体缩略图"} src={item.url ?? `/api/media/${key(item.id)}/content`}/> : <span aria-hidden="true">▧</span>}</div><div className="media-details"><strong title={item.filename}>{item.filename}</strong><div className="row"><Tag tone={item.status === "private" ? "amber" : "green"}>{item.status === "pending" ? "待验证上传" : item.status === "private" ? "私有" : "已发布"}</Tag><small>{formatBytes(item.size)}</small></div><p>{item.alt || "未填写替代文本"}</p>{item.caption && <small>图注：{item.caption}</small>}<div className="row"><button onClick={() => setEditing(item)}>编辑信息</button>{select && <button className="primary" disabled={item.status === "pending"} onClick={() => select(item)}>插入文章</button>}</div></div></div>)}</div>}{upload && <UploadMedia close={() => setUpload(false)} done={() => { setUpload(false); void resource.refresh(); }}/ >}{importOpen && <ImportMedia close={() => setImportOpen(false)} done={() => { setImportOpen(false); void resource.refresh(); }}/ >}{editing && <EditMedia item={editing} close={() => setEditing(undefined)} done={() => { setEditing(undefined); void resource.refresh(); }}/ >}</>;
}
function formatBytes(bytes: number) { return bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function UploadMedia({ close, done }: { close: () => void; done: () => void }) {
	const [file, setFile] = useState<File>(); const [alt, setAlt] = useState(""); const [caption, setCaption] = useState(""); const action = useAction();
	return <Modal title="上传私有媒体" close={close}><Field label="本地图片（最多 10 MB）"><input type="file" accept="image/png,image/jpeg,image/gif,image/webp,image/avif,image/x-icon,image/svg+xml,.ico" onChange={e => setFile(e.target.files?.[0])}/></Field>{file && <p>{file.name} · {formatBytes(file.size)}</p>}<Field label="替代文本 alt"><input value={alt} onChange={e => setAlt(e.target.value)}/></Field><Field label="图注 caption"><textarea value={caption} onChange={e => setCaption(e.target.value)} rows={2}/></Field><small className="muted">上传后仅你可见；文章发布时才会公开引用的图片。</small><ActionStatus action={action}/><button className="primary" disabled={!file || file.size > 10 * 1024 * 1024 || action.busy} onClick={() => void action.run(async () => { if (!file) return; const form = new FormData(); form.set("file", file); form.set("alt", alt); form.set("caption", caption); await api.upload("/media/upload", form); done(); }, "图片已上传到私有媒体库。")}>{action.busy ? "上传中…" : "上传到私有媒体库"}</button></Modal>;
}
function ImportMedia({ close, done }: { close: () => void; done: () => void }) { const [url, setUrl] = useState(""); const [alt, setAlt] = useState(""); const [caption, setCaption] = useState(""); const action = useAction(); return <Modal title="导入外链媒体" close={close}><Field label="HTTPS 媒体地址"><input type="url" value={url} onChange={e => setUrl(e.target.value)}/></Field><Field label="替代文本 alt"><input value={alt} onChange={e => setAlt(e.target.value)}/></Field><Field label="图注 caption"><textarea value={caption} onChange={e => setCaption(e.target.value)}/></Field><p className="muted">后台验证目标地址、类型与大小后复制至私有存储。导入不会直接公开外链。</p><ActionStatus action={action}/><button className="primary" disabled={action.busy || !/^https:\/\//i.test(url)} onClick={() => void action.run(async () => { await api.post("/media/import", { url, alt, caption }); done(); })}>导入</button></Modal>; }
function EditMedia({ item, close, done }: { item: MediaItem; close: () => void; done: () => void }) { const [alt, setAlt] = useState(item.alt); const [caption, setCaption] = useState(item.caption); const action = useAction(); return <Modal title={`媒体信息 · ${item.filename}`} close={close}><Field label="替代文本 alt"><input value={alt} onChange={e => setAlt(e.target.value)}/></Field><Field label="图注 caption"><textarea value={caption} onChange={e => setCaption(e.target.value)}/></Field><dl className="details"><dt>存储状态</dt><dd>{item.status}</dd><dt>媒体 ID</dt><dd><code>{item.id}</code></dd><dt>创建时间</dt><dd><Time value={item.createdAt}/></dd></dl><ActionStatus action={action}/><button className="primary" disabled={action.busy} onClick={() => void action.run(async () => { await api.patch(`/media/${key(item.id)}`, { alt, caption, version: item.version }); done(); })}>保存媒体信息</button></Modal>; }
